DarkSide/urls.py
from django.contrib import admin
from django.urls import path, include

import sithWay

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sithWay.urls')),
]

sithWay/urls.py
from django.urls import path

from sithWay import views
from sithWay.views import SithListView, SithListMoreThanOne

app_name = 'sithWay'
urlpatterns = [
    path('', views.selection_page, name="selection_page"),
    path('recruits/add', views.recruit_page, name="recruit_add_page"),
    path('recruits/save', views.recruit_save, name="recruit_save"),
    path('recruits/test/<int:pk>', views.recruit_test, name="recruit_test"),
    path('siths/all', SithListView.as_view(), name="sith_list"),
    path('siths/filtered/1', SithListMoreThanOne.as_view(), name="sith_list_filtered"),
    path('siths/<int:pk_sith>/all', views.sith_recruit_list, name="recruit_list"),
    path('siths/<int:pk_sith>/<int:pk_recruit>', views.sith_recruit_detail, name="recruit_detail"),
    path('siths/<int:pk_sith>/<int:pk_recruit>/make-hand-shadow', views.make_hand_shadow,
         name="recruit_make_shadow_hand"),
]

sithWay/models.py
from random import randint

from django.db import models


class Planet(models.Model):
    name = models.CharField(max_length=30, verbose_name="Планета")

    class Meta:
        verbose_name = "Планета"
        verbose_name_plural = " Планеты"

    def __str__(self):
        return self.name


class Sith(models.Model):
    name = models.CharField(max_length=40, verbose_name="Имя ситха")
    planet = models.ForeignKey(Planet, on_delete=models.CASCADE, verbose_name="Планета обучения")

    class Meta:
        verbose_name = "Ситх"
        verbose_name_plural = "Ситхи"

    def __str__(self):
        return self.name


class Recruit(models.Model):
    name = models.CharField(max_length=30, verbose_name="Имя рекрута")
    planet = models.ForeignKey(Planet, on_delete=models.CASCADE, verbose_name="Планета обитания")
    age = models.SmallIntegerField(verbose_name="Возраст рекрута")
    email = models.EmailField(verbose_name="EMail рекрута")
    teacher = models.ForeignKey(Sith, on_delete=models.CASCADE, verbose_name="Планета обитания", blank=True, null=True)

    class Meta:
        verbose_name = "Рекрут"
        verbose_name_plural = "Рекруты"


class OrderTest(models.Model):
    order = models.AutoField(primary_key=True)

    class Meta:
        verbose_name = "Орден испытания"
        verbose_name_plural = "Ордены испытания"

    def __str__(self):
        return str(self.order)


class TestQuestion(models.Model):
    order = models.ForeignKey(OrderTest, on_delete=models.CASCADE)
    question = models.TextField(verbose_name="Вопрос испытания")
    answer = models.BooleanField(verbose_name="Правильный ответ")

    class Meta:
        ordering = ('order',)
        verbose_name = "Вопрос испытания"
        verbose_name_plural = "Воспросы испытания"

    def __str__(self):
        return str(self.question)


def get_random_question_list():
    random_order = randint(1, OrderTest.objects.count())
    return TestQuestion.objects.filter(order=random_order)


class RecruitAnswer(models.Model):
    recruit = models.ForeignKey(Recruit, on_delete=models.CASCADE, verbose_name="Рекрут")
    answer = models.BooleanField(verbose_name="Ответ", blank=True, null=True)
    question = models.ForeignKey(TestQuestion, models.CASCADE, verbose_name="Вопрос")

    class Meta:
        verbose_name = "Ответ рекрута"
        verbose_name_plural = "Ответы рекрутов"

    def __str__(self):
        return self.question

sithWay/forms.py
from django import forms
from django.forms import inlineformset_factory
from sithWay.models import Recruit, RecruitAnswer


AnswerFormSet = inlineformset_factory(Recruit, RecruitAnswer, exclude=('question',),
        extra=0, can_delete=False)

class RecruitForm(forms.ModelForm):
    class Meta:
        model = Recruit
        fields = ('name', 'age', 'planet', 'email')


class RecruitAnswerForm(forms.ModelForm):
    class Meta:
        model = RecruitAnswer
        fields = ('answer', 'question', 'recruit')

sithWay/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from sithWay import forms
from sithWay.forms import RecruitForm
from sithWay.models import *


from django.views.generic import ListView

#  Отображение страницы выбора Рекрут/Ситх
def selection_page(request):
    return render(request, 'selection_page.html')


# Отображение страницы регистрации рекрута
def recruit_page(request):
    planets = Planet.objects.all()
    return render(request, 'recruit/add_recruit.html', {'planets_list': planets})


# Проверка и запись данных рекрута; перенаправление на страницу выбора ордена
def recruit_save(request):
    if request.method == 'POST':
        form_recruit = RecruitForm(request.POST)
        if form_recruit.is_valid():
            recruit = form_recruit.save()
            return redirect('sithWay:recruit_test', recruit.id)
        else:
            return redirect('sithWay:recruit_add_page')


# Подготовка записей ответов в бд
def prepare_blank_answers(recruit):
    question_list = get_random_question_list()
    for question in question_list:
        answer = RecruitAnswer(recruit=recruit, question=question)
        answer.save()


# Отображение страницы испытания для созданного рекрута
def recruit_test(request, pk):
    recruit = get_object_or_404(Recruit, id=pk)
    if len(recruit.recruitanswer_set.all()) == 0:
        prepare_blank_answers(recruit)
    if request.method == 'POST':
        formset = forms.AnswerFormSet(request.POST, instance=recruit)
        if formset.is_valid():
            formset.save()
            return redirect('sithWay:selection_page')
    else:
        formset = forms.AnswerFormSet(instance=recruit)
    return render(request, 'recruit/testHandShadow.html', {'formset': formset, 'recruit': recruit})


class SithListView(ListView):
    model = Sith
    template_name = 'sith/sith_list.html'


# def sith_list(request):
#     sith_list = Sith.objects.all()
#     return render(request, 'sith/sith_list.html', {'sith_list': sith_list})


def sith_recruit_list(request, pk_sith):
    recruit_list = Recruit.objects.filter(teacher=None)
    sith = Sith.objects.get(id=pk_sith)
    return render(request, 'sith/sith_recruit_list.html', {'recruit_list': recruit_list, 'sith': sith})


def sith_recruit_detail(request, pk_sith, pk_recruit):
    recruit = Recruit.objects.get(id=pk_recruit)
    answers = recruit.recruitanswer_set.all()
    return render(request, 'sith/recruit_detail.html', {'recruit': recruit, 'answers': answers, 'sith_pk': pk_sith})


def make_hand_shadow(request, pk_sith, pk_recruit):
    sith = Sith.objects.get(id=pk_sith)
    recruit = Recruit.objects.get(id=pk_recruit)
    if recruit.teacher:
        recruit.teacher = None;
        recruit.save()
    else:
        if (sith.recruit_set.all().count() < 3):
            recruit.teacher = sith
            recruit.save()
            send_mail('Shadow Hand Test', 'Вы приняты в ряды Ордена! Твой учитель '+sith.name+'. Он найдет тебя, когда придет время.',
                      'darksidedjango@gmail.com', [recruit.email], fail_silently=False)
    return redirect('sithWay:recruit_detail', pk_sith=sith.id, pk_recruit=recruit.id)

class SithListMoreThanOne(ListView):
    model = Sith
    context_object_name = 'sith_list'
    template_name = 'sith/sith_list.html'

    def get_queryset(self):
        sith_all_list = Sith.objects.all()
        queryset = []
        for sith in sith_all_list:
            if sith.recruit_set.all().count() > 1:
                queryset.append(sith)
        return queryset
# def sith_list_filtered(request):
#     sith_all_list = Sith.objects.all()
#     sith_list = []
#     for sith in sith_all_list:
#         if sith.recruit_set.all().count() > 1:
#             sith_list.append(sith)
#     return render(request, 'sith/sith_list_filtered.html', {'sith_list': sith_list})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Рекрутинг темной стороны</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Premium Bootstrap 4 Landing Page Template"/>
    <meta name="keywords" content="bootstrap 4, premium, clen, modern, landing, multipurpose"/>
    <meta content="Themesdesign" name="author"/>
    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.svg' %}">
    <!-- Magnific -->
    <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet" type="text/css"/>
    <!-- css -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/materialdesignicons.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Slider -->
    <link rel="stylesheet" href="{% static 'css/slick-theme.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/slick.css' %}"/>

</head>
<body>
<div class="bg-home"
     style="background-image:url({% static 'images/home/background_choice_page.jpg' %});">
    <div class="bg-overlay">
        {% block content %}

        {% endblock content %}
    </div>
</div>
</body>

</html>

templates/recruit/add_recruit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="home-center">
        <div class="home-desc-center">
            <div class="container">
                <div class="row justify-content-center">
                    <!-- Форма создания рекрута -->
                    <form action="{% url 'sithWay:recruit_save' %}" class="form-signin" method="post">
                    {% csrf_token %}
                        <!--Шапка формы -->
                        <div class="text-center mb-4">
                            <img class="mb-4 white" src="{% static 'images/favicon.svg'%}"
                                 alt="" width="72" height="72">
                            <h1 class="h3 mb-3 font-weight-normal text-white">Стать рекрутом</h1>
                            <p class="text-white">Здесь ты найдешь свое предназначение!</p>
                        </div>
                        <!-- Имя рекрута -->
                        <div class="form-label-group mb-4">
                            <input type="text" id="name" name="name" class="form-control" placeholder="Имя"
                                   required
                                   autofocus>
                        </div>

                        <!-- Возраст рекрута -->
                        <div class="form-label-group mb-4">
                            <input type="text" id="age" name="age" class="form-control" placeholder="Возраст"
                                   required
                                   autofocus>
                        </div>
                        <!-- Email рекрута-->
                        <div class="form-label-group mb-4">
                            <input type="email" id="email" name="email" class="form-control" placeholder="Email"
                                   required
                                   autofocus>
                        </div>
                        <!-- Планета обитания рекрута -->
                        <div class="form-label-group mb-4">
                            <label class="text-white" for="selectPlanet">Планета</label>
                            <select id="planet" class="form-control" name="planet" size="3" aria-label="size 3 select example">
                                {% for planet in planets_list %}
                                    <option value="{{ planet.id }}">{{ planet.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <button class="btn btn-lg btn-dark btn-block" type="submit">Подтвердить</button>

                    </form>
                    <!-- Конец формы создания рекрута -->
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/recruit/testHandShadow.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="home-center">
        <div class="home-desc-center">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="text-center mt-5 pt-4">
                            <form method="POST" class="form-signin text-white">
                                {% csrf_token %}
                                {{ formset.management_form }}
                                {% for form in formset.forms %}
                                    <h3 class="text-white">{{ form.instance.question }}</h3>
                                    {% for field in form %}
                                        {{ field|as_crispy_field }}
                                    {% endfor %}
                                {% endfor %}
                                <input class="btn btn-lg btn-dark btn-block" type="submit">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/selection_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="home-center">
        <div class="home-desc-center">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="text-center mt-5 pt-4">
                            <h1 class="heading text-white mb-3">Орден приветствует тебя!</h1>
                            <p class="text-white">Кто ты?</p>
                            <div class="mt-4 pt-2">
                                <a href="{% url 'sithWay:recruit_add_page' %}" class="btn btn-dark">Рекрут</a>
                                <a href="{% url 'sithWay:sith_list' %}" class="btn btn-dark ">Ситх</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/sith/recruit_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="home-center">
        <div class="home-desc-center">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="row text-white w-75 h-75 center">
                        <div class='col-5'>
                            <h2>{{ recruit.name }}</h2>
                            <p>Возраст: {{ recruit.age }}</p>
                            <p>Планета: {{ recruit.planet.name }}</p>
                            {% if recruit.teacher %}
                            <a href="{% url 'sithWay:recruit_make_shadow_hand' sith_pk recruit.id %}"><button type="button" class="btn btn-secondary">Убрать из учеников</button></a>
                            {% else %}
                            <a href="{% url 'sithWay:recruit_make_shadow_hand' sith_pk recruit.id %}"><button type="button" class="btn btn-secondary">Сделать рукой тени</button></a>
                            {% endif %}
                        </div>
                        <div class='col-7'>
                            <h2>Результы испытания:</h2>
                            {% for answer in answers %}
                                <h3>Вопрос: {{ answer.question.question }}</h3>
                                <div class="">
                                    {% if answer.answer == answer.question.answer %}
                                        <p class="d-inline">Ответ: {{ answer.answer }}</p>
                                        <img class ="d-inline white" src="{% static 'images/true-icon.svg'%}">
                                    {% else %}
                                        <p class="d-inline">Ответ: {{ answer.answer }}</p>
                                        <img class="d-inline white" src="{% static 'images/false-icon.svg'%}">
                                {% endif %}
                            {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/sith/sith_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="home-center">
        <div class="home-desc-center">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="cover-container d-flex p-3 mx-auto flex-column home-center">
                        <div class='list-group'>
                            {% for sith in sith_list %}
                                <a href="{% url 'sithWay:recruit_list' sith.id %}"
                                   class="list-group-item list-group-item-action" aria-current="true">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h5 class="mb-1">{{ sith.name }}</h5>
                                        <p>Рук Тени: {{ sith.recruit_set.all.count }}</p>
                                    </div>
                                    <small>Планета: {{ sith.planet.name }}</small>
                                </a>
                            {% endfor %}
                        </div>
                        <a class="mt-120" href="{% url 'sithWay:sith_list_filtered'%}">
                            <button type="button" class="btn btn-secondary">Больше 1 Руки Тени</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/sith/sith_list_filtered.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="home-center">
        <div class="home-desc-center">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="cover-container d-flex p-3 mx-auto flex-column home-center">
                        <div class='list-group'>
                            {% for sith in sith_list %}
                                <a href="{% url 'sithWay:recruit_list' sith.id %}"
                                   class="list-group-item list-group-item-action" aria-current="true">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h5 class="mb-1">{{ sith.name }}</h5>
                                        <p>Рук Тени: {{ sith.recruit_set.all.count }}</p>
                                    </div>
                                    <small>Планета: {{ sith.planet.name }}</small>
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/sith/sith_recruit_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column home-center">
        <div class="row text-white center">
            <div class="col-6">
            <h3>Рекруты: </h3>
                <div class='list-group'>
                    {% for recruit in recruit_list %}
                        <a href="{% url 'sithWay:recruit_detail' sith.id recruit.id %}"
                           class="list-group-item list-group-item-action" aria-current="true">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">{{ recruit.name }}</h5>
                            </div>
                            <p class="mb-1">Возраст: {{ recruit.age }}</p>
                            <small>Планета: {{ recruit.planet.name }}</small>
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div class="col-6 ">
                <h4>{{ sith.name }}</h4>
                <h4>Планета: {{ sith.planet.name }}</h4>
                <h3>Ученики: {{ sith.recruit_set.all.count }}</h3>
                <div class="list-group">
                    {% for recruit in sith.recruit_set.all %}
                        <a href="{% url 'sithWay:recruit_detail' sith.id recruit.id %}"
                           class="list-group-item list-group-item-action" aria-current="true">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">{{ recruit.name }}</h5>
                            </div>
                            <p class="mb-1">Возраст: {{ recruit.age }}</p>
                            <small>Планета: {{ recruit.planet.name }}</small>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}